name: Generate Report

on:
  push:
    branches:
      - main
      - pdf-final-test   # 테스트 브랜치도 허용

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PDF generator
        run: python src/generate_pdf.py

      - name: Upload generated PDF
        uses: actions/upload-artifact@v3
        with:
          name: analysis-report
          path: reports/report.pdf

